version: '3.9'

services:
  node_app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:Wf46svc49c6zGpPbUusqxXw8J9JM7pq9@dpg-cr1l5cdds78s739tman0-a/test_safj
      - REDIS_URL=redis://red-cr1l81bqf0us73fp46eg:6379
    depends_on:
      - postgres
      - redis

  node_app2:
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://user:Wf46svc49c6zGpPbUusqxXw8J9JM7pq9@dpg-cr1l5cdds78s739tman0-a/test_safj
      - REDIS_URL=redis://red-cr1l81bqf0us73fp46eg:6379
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6.2-rc-alpine
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/var/lib/redis_data/data

  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres:
  redis_data:
  pgadmin-data:
